// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// Serial is the predicate function for serial builders.
type Serial func(*sql.Selector)

// Storage is the predicate function for storage builders.
type Storage func(*sql.Selector)

// Supplier is the predicate function for supplier builders.
type Supplier func(*sql.Selector)
